//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj41143264HW2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a41143264User
    {
        public int fId { get; set; }
        public string fAccount { get; set; }
        public string fPassword { get; set; }
        public string fEmail { get; set; }
        public System.DateTime fDate { get; set; }
    }
}
