//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj41143264Linq.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NorthwindEntities : DbContext
    {
        public NorthwindEntities()
            : base("name=NorthwindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<供應商> 供應商 { get; set; }
        public virtual DbSet<員工> 員工 { get; set; }
        public virtual DbSet<客戶> 客戶 { get; set; }
        public virtual DbSet<產品資料> 產品資料 { get; set; }
        public virtual DbSet<產品類別> 產品類別 { get; set; }
        public virtual DbSet<訂貨主檔> 訂貨主檔 { get; set; }
        public virtual DbSet<訂貨明細> 訂貨明細 { get; set; }
        public virtual DbSet<貨運公司> 貨運公司 { get; set; }
    }
}
