//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj41143264Linq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 訂貨明細
    {
        public int 訂單號碼 { get; set; }
        public int 產品編號 { get; set; }
        public decimal 單價 { get; set; }
        public short 數量 { get; set; }
        public float 折扣 { get; set; }
    
        public virtual 產品資料 產品資料 { get; set; }
        public virtual 訂貨主檔 訂貨主檔 { get; set; }
    }
}
