//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj41143264ShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tMember
    {
        public int fId { get; set; }

        [DisplayName("帳號")]
        [Required]
        public string fUserId { get; set; }

        [DisplayName("密碼")]
        [Required]
        public string fPwd { get; set; }

        [DisplayName("姓名")]
        [Required]
        public string fName { get; set; }

        [DisplayName("信箱")]
        [Required]
        [EmailAddress]
        public string fEmail { get; set; }

        [DisplayName("地址")]
        [Required]
        public string fAddress { get; set; }

        [DisplayName("手機")]
        [Required]
        public string fPhone { get; set; }
    }
}
