//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj41143264.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tToDo
    {
        public int fId { get; set; }
        public string fTitle { get; set; }
        public string fLevel { get; set; }
        public Nullable<System.DateTime> fDate { get; set; }
    }
}
